-- ===========================================================================
-- Task 1c — Workspace isolation & roles (YOUR WORK GOES HERE)
-- ===========================================================================
-- This file is a STUB. The starter ships with RLS disabled (see
-- migrations/0001_init.sql) so any signed-in user can touch any workspace's
-- data. Your job: enforce, at the database level,
--
--   1. Isolation — a user only ever sees/affects workspaces they belong to.
--   2. Roles — admin (manage members + all data), member (create/edit),
--      viewer (read-only).
--
-- Enforce these in RLS policies (server-side). The UI already gates buttons by
-- role as defense-in-depth, but UI gating alone is NOT acceptable — the rules
-- must hold even if someone calls the API directly with the anon key.
--
-- Apply this file in the Supabase SQL editor once you've filled it in.
-- ---------------------------------------------------------------------------
